sites:
    ck101:
        decode : big5
        configFileLocation : "/configs/site-config/ck101-desktop.yaml"
        databaseEngine: "sqlite3"
        databaseLocation : "/database/ck101.db"
        downloadDirectory : "/books/ck101/"
        threads : 1000
        downloadBookThreads: 1000
        constSleep : 1000
        maxExploreError: 1000
        backupDirectory: "/backup/"
        useRequestInterval: false
    # 80txt:
    #     decode : utf8
    #     configFileLocation : "/configs/site-config/80txt-desktop.yaml"
    #     databaseEngine: "sqlite3"
    #     databaseLocation : "/database/80txt.db"
    #     downloadDirectory : "/books/80txt/"
    #     threads : 1000
    #     downloadBookThreads: 1000
    #     constSleep : 1000
    #     maxExploreError: 1000
    #     backupDirectory: "/backup/"
    #     useRequestInterval: false
    xqishu:
        decode : utf8
        configFileLocation : "/configs/site-config/xqishu-desktop.yaml"
        databaseEngine: "sqlite3"
        databaseLocation : "/database/xqishu.db"
        downloadDirectory : "/books/xqishu/"
        threads : 10
        downloadBookThreads: 10
        constSleep : 1000
        maxExploreError: 1000
        backupDirectory: "/backup/"
        useRequestInterval: true
    hjwzw:
        decode : utf8
        configFileLocation : "/configs/site-config/hjwzw-desktop.yaml"
        databaseEngine: "sqlite3"
        databaseLocation : "/database/hjwzw.db"
        downloadDirectory : "/books/hjwzw/"
        threads : 1000
        downloadBookThreads: 1000
        constSleep : 1000
        maxExploreError: 1000
        backupDirectory: "/backup/"
        useRequestInterval: false
    # bestory:
    #     decode : "big5"
    #     configFileLocation : "/configs/site-config/bestory-desktop.json"
    #     databaseEngine: "sqlite3"
    #     databaseLocation : "/database/bestory.db"
    #     downloadDirectory : "/mnt/addition/download/Book/bestory"
    #     threads : 1000
    #     downloadBookThreads: 1000
    #     constSleep : 1000
    #     maxExploreError: 1000
    #     backupDirectory: "/backup/"
    #     useRequestInterval: false
maxThreads: 1000
backend:
    api:
        - search
        - download
        - bookInfo
        - siteInfo
        - random
        - process
        - info
    stageFile: '/log/stage.txt'
    logFile: '/log/batch.log'
