sites:
    test:
        decode: big5
        configFileLocation: "/test-data/book-config.yml"
        databaseEngine: "sqlite3"
        databaseLocation: "./test.db"
        downloadDirectory: "/test-data/storage/"
        threadsCount: 1000
        downloadThreadsCount: 5
        constSleep: 1000
        maxExploreError: 1000
        backupDirectory: "/test-data/"
        useRequestInterval: true
maxThreads: 1000
backend:
    api:
        - search
        - download
        - bookInfo
        - siteInfo
        - random
        - process
        - info
    stageFile: '/log/stage.txt'
    logFile: '/log/controller.log'
