version: "3.7"

services:
    #TODO: build image and push to ghcr
    api:
        build: 
            context: ./backend
            dockerfile: ./build/Dockerfile.api
        deploy:
            resources:
                limits:
                    memory: '500M'
        hostname: bookspider_backend
        volumes:
            - ./bin/database:/database
            - ./bin/log:/log
            - type: bind
              source: /mnt/addition/download/Books
              target: /books
            - ./backend/config/v2:/config
            - ./backend/database/migrations:/migrations
        env_file:
            - ./backend/assets/.env.api
        networks:
            - router
            - database
        ports:
            - 9427:9427

    frontend:
        build:
            context: ./frontend
        deploy:
            resources:
                limits:
                    memory: '1G'
        volumes:
            - frontend_volume:/build-result/web
            - ./frontend/src:/usr/src/app
        networks:
            - router
        profiles:
            - all
            - frontend
            - web
        env_file:
            - ./.env
        command: sh -c "flutter --version ; flutter pub get ; flutter build web --base-href $NOVEL_SPIDER_FE_ROUTE_PREFIX/ --dart-define=NOVEL_SPIDER_API_HOST=$NOVEL_SPIDER_API_HOST --dart-define=NOVEL_SPIDER_API_ROUTE_PREFIX=$NOVEL_SPIDER_API_ROUTE_PREFIX --dart-define=NOVEL_SPIDER_FE_ROUTE_PREFIX=$NOVEL_SPIDER_FE_ROUTE_PREFIX"
    
    #TODO: build image and push to ghcr
    worker:
        build: 
            context: ./backend
            dockerfile: ./build/Dockerfile.worker
        deploy:
            resources:
                limits:
                    cpus: '3.0'
                    memory: '3G'
        volumes:
            - ./bin/log:/log
            - type: bind
              source: /mnt/addition/download/Books
              target: /books
            - ./bin/backup:/backup
            - ./backend/config/v2:/config
            # - ./backend/assets/api_parser:/api_parser
            - ./backend/database/migrations:/migrations
        env_file:
            - ./backend/assets/.env.worker
        networks:
            - database

    console:
        build: 
            context: ./backend
            dockerfile: ./build/Dockerfile.console
        deploy:
            resources:
                limits:
                    cpus: '3.0'
                    memory: '3G'
        volumes:
            - ./bin/log:/log
            - type: bind
              source: /mnt/addition/download/Books
              target: /books
            - ./bin/backup:/backup
            - ./backend/config/v2:/config
            # - ./backend/assets/api_parser:/api_parser
            - ./backend/database/migrations:/migrations
        env_file:
            - ./backend/assets/.env
            - .env
        networks:
            - database
        profiles:
            - all
            - console
        command: sh -c "./console --operation ${command} ${params} >> /log/console.log 2>&1"

volumes:
    frontend_volume:
        name: novel_frontend_volume

networks:
    router:
        driver: bridge
        name: router
    default:
    database:
        name: database
        external: true
