version: "3.7"

services:
    backend:
        build: 
            context: ./backend
            dockerfile: ./build/Dockerfile.backend
        volumes:
            - ./bin/database:/database
            - ./bin/log:/log
            - /mnt/addition/download/Books:/books
            - ./bin/configs:/configs
        environment:
            - ASSETS_LOCATION=
        networks:
            - router
        profiles:
            - all
            - backend
            - web
        command: sh -c "./backend > /log/backend.log 2>&1"

    controller:
        build:
            context: ./backend
            dockerfile: ./build/Dockerfile.controller
        volumes:
            - ./bin/database:/database
            - ./bin/log:/log
            - /mnt/addition/download/Books:/books
            - ./bin/backup:/backup
            - ./bin/configs:/configs
        environment:
            - ASSETS_LOCATION=
        networks:
            - router
        profiles:
            - all
            - controller
        command: sh -c "./controller --operation ${command} ${params} >> /log/controller.log 2>&1"

    frontend:
        image: "flutter:latest"
        volumes:
            - frontend_volume:/build/web
            - ./frontend/src:/usr/src/app
        networks:
            - router
        profiles:
            - all
            - frontend
            - web
        command: sh -c "flutter --version ; flutter pub get ; flutter build web"
    
    backend_test:
        build:
            context: ./backend
            dockerfile: ./build/Dockerfile.test
        profiles:
            - all
            - test
        command: >
            sh -c "
                go test github.com/htchan/BookSpider/internal/logging
                go test github.com/htchan/BookSpider/internal/database
                go test github.com/htchan/BookSpider/internal/database/sqlite
                go test github.com/htchan/BookSpider/internal/utils
                go test github.com/htchan/BookSpider/pkg/configs
                go test github.com/htchan/BookSpider/pkg/books
                go test github.com/htchan/BookSpider/pkg/flags
                go test github.com/htchan/BookSpider/pkg/sites
                go test github.com/htchan/BookSpider/cmd/backend
                go test github.com/htchan/BookSpider/cmd/controller
            "
    temp:
        image: alpine:latest
        profiles:
            - temp
        volumes:
            - ./bin/log:/log
        command: sh -c 'cp /log/test.txt /log/$$(date +"%Y-%m-%d--%T").log'


volumes:
    frontend_volume:
        name: novel_frontend_volume

networks:
    router:
        driver: bridge
        name: router
