version: "3.7"

services:
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile.backend
        volumes:
            - ./bin/database:/database
            - ./bin/log:/log
            - /mnt/addition/download/Books:/books
        networks:
            - router
        profiles:
            - all
            - backend
            - web
        command: sh -c "./backend > /log/backend.log"

    controller:
        build:
            context: ./backend
            dockerfile: Dockerfile.controller
        volumes:
            - ./bin/database:/database
            - ./bin/log:/log
            - /mnt/addition/download/Books:/books
            - ./bin/backup:/backup
        networks:
            - router
        profiles:
            - all
            - controller
        command: sh -c "./controller --operation ${command} ${params} >> /log/controller.log"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.flutter
        volumes:
            - frontend_volume:/build/web
            - ./frontend/src:/usr/src/app
        networks:
            - router
        profiles:
            - all
            - frontend
            - web
        command: sh -c "flutter --version ; flutter pub get ; flutter build web"
    
    backend_test:
        build:
            context: ./backend
            dockerfile: Dockerfile.test
        profiles:
            - all
            - test
        command: "go test github.com/htchan/BookSpider/helper \
		    github.com/htchan/BookSpider/model \
		    github.com/htchan/BookSpider/public -v"

volumes:
    frontend_volume:
        name: novel_frontend_volume

networks:
    router:
        driver: bridge
        name: router