FROM golang:1.16.4-alpine3.13 as builder

WORKDIR /usr/src/app

COPY ./src .

COPY Makefile .

RUN make backend


FROM golang:1.16.3-alpine3.13

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/backend .

COPY -- from=builder /usr/src/app/public/config .

CMD ['./backend']