// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package sqlc

import (
	"database/sql"
)

type Book struct {
	Site           sql.NullString
	ID             sql.NullInt32
	HashCode       sql.NullInt32
	Title          sql.NullString
	WriterID       sql.NullInt32
	Type           sql.NullString
	UpdateDate     sql.NullString
	UpdateChapter  sql.NullString
	Status         sql.NullString
	IsDownloaded   sql.NullBool
	Checksum       sql.NullString
	WriterChecksum sql.NullString
}

type Error struct {
	Site sql.NullString
	ID   sql.NullInt32
	Data sql.NullString
}

type Writer struct {
	ID       int32
	Name     sql.NullString
	Checksum sql.NullString
}
