ALTER TABLE books ALTER COLUMN site SET NOT NULL;
ALTER TABLE books ALTER COLUMN id SET NOT NULL;
ALTER TABLE books ALTER COLUMN hash_code SET NOT NULL;
ALTER TABLE books ALTER COLUMN status SET NOT NULL;
ALTER TABLE books ALTER COLUMN is_downloaded SET NOT NULL;
