default_rate_limit_config: &default_rate_limit_config
  queue_size: 1000
  interval: 1s

xbiquge_client: &xbiquge_client
  rate_limit: *default_rate_limit_config
  circuit_breaker: *default_circuit_breaker_config
  retry: *default_retry_config

xqishu_client: &xqishu_client
  rate_limit:
    queue_size: 200
    interval: 1s
  circuit_breaker:
    <<: *default_circuit_breaker_config
    failure_threshold: 10
  retry: *default_retry_config

80txt_client: &80txt_client
  rate_limit: *default_rate_limit_config
  circuit_breaker: *default_circuit_breaker_config
  retry: *default_retry_config

bestory_client: &bestory_client
  rate_limit: *default_rate_limit_config
  circuit_breaker: *default_circuit_breaker_config
  retry: *default_retry_config

ck101_client: &ck101_client
  rate_limit: *default_rate_limit_config
  circuit_breaker: *default_circuit_breaker_config
  retry: *default_retry_config

hjwzw_client: &hjwzw_client
  rate_limit: *default_rate_limit_config
  circuit_breaker: *default_circuit_breaker_config
  retry: *default_retry_config

uukanshu_client: &uukanshu_client
  rate_limit: *default_rate_limit_config
  circuit_breaker: *default_circuit_breaker_config
  retry: *default_retry_config
