apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: book-spider.api  # Sets Deployment name
  namespace: default
  labels:
    app: api
    project: book-spider
resources:
  - ./base/deployment.yml
  - ./base/service.yml
  - ./base/ingress.yml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: book-spider.api
      labelSelector: "app=api,project=book-spider"
    path: ./patch/deployment.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: book-spider-api-ingress
    path: ./patch/ingress.yml
secretGenerator:
- name: book-spider.api.secret
  type: Opaque
  envs:
  - ./patch/.env
