ALTER TABLE books ALTER COLUMN site DROP NOT NULL;
ALTER TABLE books ALTER COLUMN id DROP NOT NULL;
ALTER TABLE books ALTER COLUMN hash_code DROP NOT NULL;
ALTER TABLE books ALTER COLUMN status DROP NOT NULL;
ALTER TABLE books ALTER COLUMN is_downloaded DROP NOT NULL;
