metaBaseUrl : "https://www.balingtxt.com/txtml_%v.html",
metaDownloadUrl : "http://www.balingtxt.com/txtml_%v.html",
metaChapterUrl : "%v",
chapterPattern : "http://www.xqiushu.com/.*?\\.html",
titleRegex : "<h1>(.*?)全文阅读</h1>",
writerRegex : "作者：<a.*?>(.*?)</a>",
typeRegex : "分类：<a.*?>(.*?)</a>",
lastUpdateRegex : "(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})",
lastChapterRegex : "(?s)<li><a.*>(.*?)</a></li>.</div>",
chapterUrlRegex : "<li><a.*?href=\"(.*?)\".*?>.*?</a></li>",
chapterTitleRegex : "<li><a.*?>(.*?)</a></li>",
chapterContentRegex : "(?s)<div.*?book_content.*?>(.*?)</div>"