sites:
    ck101:
        decode : big5
        configLocation : "./config/ck101-desktop.yaml"
        databaseLocation : "./database/ck101.db"
        downloadLocation : "/mnt/addition/download/Books/ck101/"
    80txt:
        decode : utf8
        configLocation : "./config/80txt-desktop.yaml"
        databaseLocation : "./database/80txt.db"
        downloadLocation : "/mnt/addition/download/Books/80txt/"
    xqishu:
        decode : utf8
        configLocation : "./config/xqishu-desktop.yaml"
        databaseLocation : "./database/xqishu.db"
        downloadLocation : "/mnt/addition/download/Books/xqishu/"
    hjwzw:
        decode : utf8
        configLocation : "./config/hjwzw-desktop.yaml"
        databaseLocation : "./database/hjwzw.db"
        downloadLocation : "/mnt/addition/download/Books/hjwzw/"
    # bestory:
    #     decode : "big5"
    #     configLocation : "./config/bestory-desktop.json"
    #     databaseLocation : "./database/bestory.db"
    #     downloadLocation : "/mnt/addition/download/Book/bestory"
api:
  - search
  - download
  - bookInfo
  - siteInfo
  - random
  - process
  - info
