// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Book struct {
	Site           string
	ID             int32
	HashCode       int32
	Title          sql.NullString
	WriterID       sql.NullInt32
	Type           sql.NullString
	UpdateDate     sql.NullString
	UpdateChapter  sql.NullString
	Status         string
	IsDownloaded   bool
	Checksum       sql.NullString
	WriterChecksum sql.NullString
}

type Error struct {
	Site sql.NullString
	ID   sql.NullInt32
	Data sql.NullString
}

type Writer struct {
	ID       int32
	Name     sql.NullString
	Checksum sql.NullString
}
