baseUrl : "https://base-url/%v"
downloadUrl : "https://download-url/%v"
chapterUrl : "https://chapter-url/%v"
chapterUrlPattern : "chapter-url-pattern"
titleRegex : "(title-regex)"
writerRegex : "(writer-regex)"
typeRegex : "(type-regex)"
lastUpdateRegex : "(last-update-regex)"
lastChapterRegex : "(last-chapter-regex)"
chapterUrlRegex : "chapter-url-regex-(\\d)"
chapterTitleRegex : "chapter-title-regex-(\\d)"
chapterContentRegex : "chapter-content-(.*)-content-regex"
