sites:
  xbiquge:
    <<: *xbiquge_selector
    client: *xbiquge_client
    decode_method: gbk
    max_threads: 1500
    request_timeout: 30s

    storage: "/books/xbiquge"
    backup_directory: /backup/book_spider

    max_explore_error: 1000
    max_download_concurrency: 5

  xqishu:
    <<: *xqishu_selector
    client: *xqishu_client
    decode_method: utf8
    max_threads: 500
    request_timeout: 30s

    storage: "/books/xqishu"
    backup_directory: /backup/book_spider

    max_explore_error: 500
    max_download_concurrency: 5

  80txt:
    <<: *80txt_selector
    client: *80txt_client
    decode_method: utf8
    max_threads: 1500
    request_timeout: 30s

    storage: "/books/80txt"
    backup_directory: /backup/book_spider

    max_explore_error: 100
    max_download_concurrency: 5

  bestory:
    <<: *bestory_selector
    client: *bestory_client
    decode_method: big5
    max_threads: 1500
    request_timeout: 30s

    storage: "/books/bestory"
    backup_directory: /backup/book_spider

    max_explore_error: 100
    max_download_concurrency: 5

  ck101:
    <<: *ck101_selector
    client: *ck101_client
    decode_method: big5
    max_threads: 1500
    request_timeout: 30s

    storage: "/books/ck101"
    backup_directory: /backup/book_spider

    max_explore_error: 100
    max_download_concurrency: 5

  hjwzw:
    <<: *hjwzw_selector
    client: *hjwzw_client
    decode_method: utf8
    max_threads: 1500
    request_timeout: 30s

    storage: "/books/hjwzw"
    backup_directory: /backup/book_spider

    max_explore_error: 100
    max_download_concurrency: 5

  uukanshu:
    <<: *uukanshu_selector
    client: *uukanshu_client
    decode_method: gbk
    max_threads: 1500
    request_timeout: 30s

    storage: "/books/uukanshu"
    backup_directory: /backup/book_spider

    max_explore_error: 100
    max_download_concurrency: 20
