// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/htchan/BookSpider/internal/client/v1 (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/client/v1/client.go -package=mockclient . Client
//

// Package mockclient is a generated GoMock package.
package mockclient

import (
	context "context"
	reflect "reflect"

	client "github.com/htchan/BookSpider/internal/client/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Available mocks base method.
func (m *MockClient) Available(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Available", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Available indicates an expected call of Available.
func (mr *MockClientMockRecorder) Available(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Available", reflect.TypeOf((*MockClient)(nil).Available), ctx)
}

// GetBookChapterList mocks base method.
func (m *MockClient) GetBookChapterList(ctx context.Context, bookID string) (client.ChapterEntryList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookChapterList", ctx, bookID)
	ret0, _ := ret[0].(client.ChapterEntryList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookChapterList indicates an expected call of GetBookChapterList.
func (mr *MockClientMockRecorder) GetBookChapterList(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookChapterList", reflect.TypeOf((*MockClient)(nil).GetBookChapterList), ctx, bookID)
}

// GetBookInfo mocks base method.
func (m *MockClient) GetBookInfo(ctx context.Context, bookID string) (*client.BookInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookInfo", ctx, bookID)
	ret0, _ := ret[0].(*client.BookInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookInfo indicates an expected call of GetBookInfo.
func (mr *MockClientMockRecorder) GetBookInfo(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookInfo", reflect.TypeOf((*MockClient)(nil).GetBookInfo), ctx, bookID)
}

// GetChapterContent mocks base method.
func (m *MockClient) GetChapterContent(ctx context.Context, chapter client.ChapterEntry) (*client.ChapterContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChapterContent", ctx, chapter)
	ret0, _ := ret[0].(*client.ChapterContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChapterContent indicates an expected call of GetChapterContent.
func (mr *MockClientMockRecorder) GetChapterContent(ctx, chapter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChapterContent", reflect.TypeOf((*MockClient)(nil).GetChapterContent), ctx, chapter)
}
