apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-spider.api  # Sets Deployment name
  labels:
    app: api
    project: book-spider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        project: book-spider
    spec:
      containers:
        - name: book-spider-api
          image: ghcr.io/htchan/book-spider:initial # Sets Image
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 50M
            requests:
              memory: 15M
          envFrom:
            - secretRef:
                name: book-spider.api.secret
          volumeMounts:
            - mountPath: /config
              name: book-spider-config-volume
            - mountPath: /migrations
              name: book-spider-migrations-volume
            - mountPath: /log
              name: book-spider-log-volume
            - mountPath: /books
              name: book-spider-data-volume
        - name: book-spider-log-collector
          image: grafana/fluent-bit-plugin-loki
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 30M
            requests:
              memory: 10M
          args:
            - "/fluent-bit/bin/fluent-bit"
            - "-R"
            - "/fluent-bit/etc/fluent-bit-config/parsers.conf"
            - "-e"
            - "/fluent-bit/bin/out_grafana_loki.so"
            - "-c"
            - "/fluent-bit/etc/fluent-bit-config/fluent-bit.conf"
          volumeMounts:
            - mountPath: /log
              name: book-spider-log-volume
            - mountPath: /fluent-bit/etc/fluent-bit-config
              name: book-spider-flunt-bit-config-volume
      volumes:
        - name: book-spider-config-volume
          persistentVolumeClaim:
            claimName: book-spider.config-claim
        - name: book-spider-migrations-volume
          persistentVolumeClaim:
            claimName: book-spider.migrations-claim
        - name: book-spider-log-volume
          persistentVolumeClaim:
            claimName: book-spider.log-claim
        - name: book-spider-data-volume
          persistentVolumeClaim:
            claimName: book-spider.data-claim
        - name: book-spider-flunt-bit-config-volume
          configMap:
            name: book-spider.fluent-bit.config
      restartPolicy: Always
