apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-spider.api  # Sets Deployment name
  labels:
    app: api
    project: book-spider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        project: book-spider
    spec:
      containers:
        - name: book-spider-api
          image: ghcr.io/htchan/book-spider:initial # Sets Image
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 50M
            requests:
              memory: 15M
          envFrom:
            - secretRef:
                name: book-spider.api.secret
          volumeMounts:
            - mountPath: /config
              name: book-spider-config-volume
            - mountPath: /migrations
              name: book-spider-migrations-volume
            - mountPath: /log
              name: book-spider-log-volume
            - mountPath: /books
              name: book-spider-data-volume
      volumes:
        - name: book-spider-config-volume
          persistentVolumeClaim:
            claimName: book-spider.config-claim
        - name: book-spider-migrations-volume
          persistentVolumeClaim:
            claimName: book-spider.migrations-claim
        - name: book-spider-log-volume
          persistentVolumeClaim:
            claimName: book-spider.log-claim
        - name: book-spider-data-volume
          persistentVolumeClaim:
            claimName: book-spider.data-claim
      restartPolicy: Always
