baseUrl : "https://www.80xs.la/txtml_%v.html"
downloadUrl : "http://www.80xs.la/txtml_%v.html"
chapterUrl : "%v"
chapterUrlPattern : "http://www.aidusk.com/.*?\\.html"
titleRegex : "<h1>(.*?)全文阅读</h1>"
writerRegex : "作者：<a.*?>(.*?)</a>"
typeRegex : "分类：<a.*?>(.*?)</a>"
lastUpdateRegex : "(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})"
lastChapterRegex : "(?s)<li><a.*>(.*?)</a></li>.</div>"
chapterUrlRegex : "<li><a.*?href=\"(http.*?)\">.*?</a></li>"
chapterTitleRegex : "<li><a.*?href=\"http.*?\">(.*?)</a></li>"
chapterContentRegex : "(?s)<div.*?book_content.*?>(.*?)</div>"
