baseUrl : "https://www.book100.com/book/book%v.html"
downloadUrl : "https://www.book100.com/book/book%v.html"
chapterUrl : "https://www.book100.com/%v"
chapterUrlPattern : "/novel.*?\\.html"
titleRegex : "<title>(.*?) 在線觀看</title>"
writerRegex : "作者:<font.*?>(.*?)</font>"
typeRegex : "<a href='/category/\\d+.html' id='cat\\d+' class=\"nav\" >(.*?)</a>"
lastUpdateRegex : "更新: <b><font.*?>(.*?)</font></b>"
lastChapterRegex : "(?s).*<a.*?>(.*?)</a> <font.*?></font>"
chapterUrlRegex : "<td.*?><a href=\"(.*?)\".*?>.*?</a>.*?</td>"
chapterTitleRegex : "<td.*?><a.*?>(.*?)</a>.*?</td>"
chapterContentRegex : "(?s)<p class=\"content\">(.*?)</p>"
