baseUrl : "http://www.aidusk.com/txt%v/"
downloadUrl : "http://www.aidusk.com/t/%v/"
chapterUrl : "http://www.aidusk.com%v"
chapterUrlPattern : "/t/.*?\\.html"
titleRegex : "<div class=\"tit1\"><h1>(.*?)</h1>"
writerRegex : "<span>小说作者：(.*?)</span>"
typeRegex : "(?s)<div class=\"crumbs\">.*?<a href=\"/ls/.*?html\">(.*?)</a>"
lastUpdateRegex : "<span>更新日期：(.*?)</span>"
lastChapterRegex : "<h3>最新章节：<a.*?>(.*?)</a>.*?</h3>"
chapterUrlRegex : "<li><a href=\"(\\d+?.html)\">.*?</a></li>"
chapterTitleRegex : "<li><a href=\"\\d+?.html\">(.*?)</a></li>"
chapterContentRegex : "(?s)<div.*?book_content.*?>(.*?)</div>"