// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/htchan/BookSpider/internal/service/v1 (interfaces: BookService)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/service/v1/book_service.go -package=mockservice . BookService
//

// Package mockservice is a generated GoMock package.
package mockservice

import (
	context "context"
	reflect "reflect"

	model "github.com/htchan/BookSpider/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockBookService is a mock of BookService interface.
type MockBookService struct {
	ctrl     *gomock.Controller
	recorder *MockBookServiceMockRecorder
	isgomock struct{}
}

// MockBookServiceMockRecorder is the mock recorder for MockBookService.
type MockBookServiceMockRecorder struct {
	mock *MockBookService
}

// NewMockBookService creates a new mock instance.
func NewMockBookService(ctrl *gomock.Controller) *MockBookService {
	mock := &MockBookService{ctrl: ctrl}
	mock.recorder = &MockBookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookService) EXPECT() *MockBookServiceMockRecorder {
	return m.recorder
}

// DownloadBook mocks base method.
func (m *MockBookService) DownloadBook(arg0 context.Context, arg1 *model.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadBook", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadBook indicates an expected call of DownloadBook.
func (mr *MockBookServiceMockRecorder) DownloadBook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadBook", reflect.TypeOf((*MockBookService)(nil).DownloadBook), arg0, arg1)
}

// ProcessBook mocks base method.
func (m *MockBookService) ProcessBook(arg0 context.Context, arg1 *model.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessBook", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessBook indicates an expected call of ProcessBook.
func (mr *MockBookServiceMockRecorder) ProcessBook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessBook", reflect.TypeOf((*MockBookService)(nil).ProcessBook), arg0, arg1)
}

// SupportBook mocks base method.
func (m *MockBookService) SupportBook(arg0 *model.Book) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportBook", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportBook indicates an expected call of SupportBook.
func (mr *MockBookServiceMockRecorder) SupportBook(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportBook", reflect.TypeOf((*MockBookService)(nil).SupportBook), arg0)
}

// UpdateBook mocks base method.
func (m *MockBookService) UpdateBook(arg0 context.Context, arg1 *model.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockBookServiceMockRecorder) UpdateBook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockBookService)(nil).UpdateBook), arg0, arg1)
}
