apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: book-spider.api  # Sets Deployment name
  namespace: default
  labels:
    app: api
    project: book-spider
resources:
  - ./base/deployment.yml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: book-spider.worker
      labelSelector: "app=worker,project=book-spider"
    path: ./patch/deployment.yml
secretGenerator:
- name: book-spider.worker.secret
  type: Opaque
  envs:
  - ./patch/.env
