sites:
    ck101:
        decode : big5
        configFileLocation : "/configs/site-config/ck101-desktop.yaml"
        databaseEngine: "sqlite3"
        databaseLocation : "/database/ck101.db"
        downloadDirectory : "/books/ck101/"
        threadsCount : 1000
        downloadThreadsCount: 5
        constSleep : 1000
        maxExploreError: 1000
        backupDirectory: "/backup/"
    # 80txt:
    #     decode : utf8
    #     configFileLocation : "/configs/site-config/80txt-desktop.yaml"
    #     databaseEngine: "sqlite3"
    #     databaseLocation : "/database/80txt.db"
    #     downloadDirectory : "/books/80txt/"
    #     threadsCount : 1000
    #     downloadThreadsCount: 5
    #     constSleep : 1000
    #     maxExploreError: 1000
    #     backupDirectory: "/backup/"
    xqishu:
        decode : utf8
        configFileLocation : "/configs/site-config/xqishu-desktop.yaml"
        databaseEngine: "sqlite3"
        databaseLocation : "/database/xqishu.db"
        downloadDirectory : "/books/xqishu/"
        threadsCount : 2
        downloadThreadsCount: 5
        constSleep : 1000
        maxExploreError: 1000
        backupDirectory: "/backup/"
    hjwzw:
        decode : utf8
        configFileLocation : "/configs/site-config/hjwzw-desktop.yaml"
        databaseEngine: "sqlite3"
        databaseLocation : "/database/hjwzw.db"
        downloadDirectory : "/books/hjwzw/"
        threadsCount : 1000
        downloadThreadsCount: 5
        constSleep : 1000
        maxExploreError: 1000
        backupDirectory: "/backup/"
    # bestory:
    #     decode : "big5"
    #     configFileLocation : "/configs/site-config/bestory-desktop.json"
    #     databaseEngine: "sqlite3"
    #     databaseLocation : "/database/bestory.db"
    #     downloadDirectory : "/mnt/addition/download/Book/bestory"
    #     threadsCount : 1000
    #     downloadThreadsCount: 5
    #     constSleep : 1000
    #     maxExploreError: 1000
    #     backupDirectory: "/backup/"
maxThreads: 1000
backend:
    api:
        - search
        - download
        - bookInfo
        - siteInfo
        - random
        - process
        - info
    stageFile: '/log/stage.txt'
    logFile: '/log/controller.log'
