kind: PersistentVolume
apiVersion: v1
metadata:
  name: book-spider.config-volume
  labels:
    label: local
    project: book-spider
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /volumes/book-spider-data/config
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: book-spider.migrations-volume
  labels:
    label: local
    project: book-spider
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /volumes/book-spider-data/migrations
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: book-spider.log-volume
  labels:
    label: local
    project: book-spider
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /volumes/book-spider-data/log
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: book-spider.data-volume
  labels:
    label: local
    project: book-spider
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /volumes/book-spider-data/data
