apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: book-spider.config-claim # Sets name of PV
  labels:
    project: book-spider
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 50Gi # Sets volume size
  volumeName: book-spider.config-volume
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: book-spider.migrations-claim # Sets name of PV
  labels:
    project: book-spider
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 50Gi # Sets volume size
  volumeName: book-spider.migrations-volume
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: book-spider.log-claim # Sets name of PV
  labels:
    project: book-spider
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 50Gi # Sets volume size
  volumeName: book-spider.log-volume
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: book-spider.data-claim # Sets name of PV
  labels:
    project: book-spider
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 50Gi # Sets volume size
  volumeName: book-spider.data-volume
